mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.huxin.tools.entity,com.huxin.tools.vo
  mapper-locations: classpath:mybatis/*Mapper.xml
#  config-location: classpath:mybatis-config.xml
#  check-config-location: true

spring:
  thymeleaf:
    cache: false

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.22.131/tools?useUnicode=true&characterEncoding=UTF-8
    username: tools
    password: tools

logging:
  level:
        com.huxin.tools.dao: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"


